import type { OilPattern } from '@/lib/types/oil';

export const OIL_PATTERNS: OilPattern[] = [
  {
    name: 'House Shot',
    length: 40,
    difficulty: 'Easy',
    description: 'The standard house shot used in most recreational bowling centers. Oil is concentrated in the middle with dry boards on the outside.',
    tip: 'Play the 10–15 board and let the pattern funnel your ball to the pocket.',
    ratio: '8:1',
  },
  {
    name: 'Sport Shot',
    length: 42,
    difficulty: 'Sport',
    description: 'A flatter oil pattern with less outside oil than a house shot. Requires more accuracy and precision.',
    tip: 'Stay straighter and avoid over-hooking. Target the 12–17 board.',
    ratio: '3:1',
  },
  {
    name: 'Cheetah',
    length: 35,
    difficulty: 'Hard',
    description: 'A short WTBA sport pattern (35 ft). The short length demands a controlled release and early hook.',
    tip: 'Play straighter and inside. Reduce rev rate and use a weaker ball.',
    ratio: '2.7:1',
  },
  {
    name: 'Chameleon',
    length: 41,
    difficulty: 'Hard',
    description: 'A medium-length WTBA sport pattern that transitions quickly. Ball choice and timing are critical.',
    tip: 'Start on the 15 board and move left as the pattern transitions.',
    ratio: '2.9:1',
  },
  {
    name: 'Scorpion',
    length: 45,
    difficulty: 'Hard',
    description: 'A longer WTBA sport pattern (45 ft). Favors higher rev players who can carry the ball deep.',
    tip: 'Use a high-hooking ball and play deep inside angles. Target the 20+ boards.',
    ratio: '2.7:1',
  },
  {
    name: 'Shark',
    length: 48,
    difficulty: 'Sport',
    description: 'The longest WTBA sport pattern (48 ft). Extremely demanding with little outside forgiveness.',
    tip: 'Play very deep inside. This pattern is designed to expose ball speed and axis tilt weaknesses.',
    ratio: '2.5:1',
  },
  {
    name: 'Viper',
    length: 37,
    difficulty: 'Hard',
    description: 'A short-medium WTBA sport pattern. The dry outside creates a steep hook angle if you miss outside.',
    tip: 'Keep your ball speed up and play a straighter line at 10–12 boards.',
    ratio: '2.6:1',
  },
  {
    name: 'Christmas Tree',
    length: 40,
    difficulty: 'Medium',
    description: 'A medium-length recreational pattern with moderate oil ratio. Slightly more challenging than the house shot.',
    tip: 'Play 12–14 boards and look for the ball to make a smooth arc to the pocket.',
    ratio: '5:1',
  },
  {
    name: 'PBA Experience',
    length: 44,
    difficulty: 'Hard',
    description: 'Simulates conditions used on the PBA Tour. Demands consistent targeting and carry-down management.',
    tip: 'Track your carry-down carefully. Move left as the backends dry up.',
    ratio: '3.2:1',
  },
  {
    name: 'Badger',
    length: 52,
    difficulty: 'Sport',
    description: 'One of the longest patterns used in competition. Requires a very clean backend to generate hook.',
    tip: 'Use a high-surface, high-hook ball. Play inside 25 boards and let the ball breathe at the breakpoint.',
    ratio: '2.4:1',
  },
];
